import type { Metadata, Viewport } from 'next';
import './globals.css';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: '#fcd309', // 👉 la couleur de la barre du navigateur
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        {/* ✅ meta moderne pour Android Chrome */}
        <meta name="mobile-web-app-capable" content="yes" />
        {/* ✅ meta pour Safari (toujours compatible, mais plus clean) */}
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="Echimine" />
      </head>
      <body className="bg-white antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
